export const getBankName = (bankCode: string): string => {
  const bankNames: { [key: string]: string } = {
    '033': 'United Bank for Africa (UBA)',
    '044': 'Access Bank',
    '058': 'Guaranty Trust Bank',
    '011': 'First Bank of Nigeria',
    '032': 'Union Bank of Nigeria',
    '050': 'Ecobank Nigeria',
    '070': 'Fidelity Bank',
    '082': 'Keystone Bank',
    '084': 'Unity Bank',
    '090': 'Heritage Bank',
    '101': 'Providus Bank',
    '102': 'Titan Trust Bank',
    '103': 'Globus Bank',
    '104': 'Parallex Bank',
    '107': 'Suntrust Bank',
    '110': 'Stanbic IBTC Bank',
    '112': 'Citibank Nigeria',
    '113': 'First City Monument Bank',
    '114': 'Wema Bank',
    '119': 'Jaiz Bank',
    '120': 'Heritage Bank',
    '121': 'Keystone Bank',
    '122': 'Unity Bank',
    '123': 'Zenith Bank',
    '124': 'Standard Chartered Bank',
    '125': 'Sterling Bank',
    '126': 'Polaris Bank',
    '127': 'Titan Trust Bank',
    '128': 'Providus Bank',
    '129': 'Globus Bank',
    '130': 'Parallex Bank',
    '131': 'Suntrust Bank',
    '132': 'Stanbic IBTC Bank',
    '133': 'Citibank Nigeria',
    '134': 'First City Monument Bank',
    '135': 'Wema Bank',
    '136': 'Jaiz Bank',
    '137': 'Heritage Bank',
    '138': 'Keystone Bank',
    '139': 'Unity Bank',
    '140': 'Zenith Bank',
    '141': 'Standard Chartered Bank',
    '142': 'Sterling Bank',
    '143': 'Polaris Bank',
    '144': 'Titan Trust Bank',
    '145': 'Providus Bank',
    '146': 'Globus Bank',
    '147': 'Parallex Bank',
    '148': 'Suntrust Bank',
    '149': 'Stanbic IBTC Bank',
    '150': 'Citibank Nigeria',
    '151': 'First City Monument Bank',
    '152': 'Wema Bank',
    '153': 'Jaiz Bank',
    '154': 'Heritage Bank',
    '155': 'Keystone Bank',
    '156': 'Unity Bank',
    '157': 'Zenith Bank',
    '158': 'Standard Chartered Bank',
    '159': 'Sterling Bank',
    '160': 'Polaris Bank',
    '161': 'Titan Trust Bank',
    '162': 'Providus Bank',
    '163': 'Globus Bank',
    '164': 'Parallex Bank',
    '165': 'Suntrust Bank',
    '166': 'Stanbic IBTC Bank',
    '167': 'Citibank Nigeria',
    '168': 'First City Monument Bank',
    '169': 'Wema Bank',
    '170': 'Jaiz Bank',
    '171': 'Heritage Bank',
    '172': 'Keystone Bank',
    '173': 'Unity Bank',
    '174': 'Zenith Bank',
    '175': 'Standard Chartered Bank',
    '176': 'Sterling Bank',
    '177': 'Polaris Bank',
    '178': 'Titan Trust Bank',
    '179': 'Providus Bank',
    '180': 'Globus Bank',
    '181': 'Parallex Bank',
    '182': 'Suntrust Bank',
    '183': 'Stanbic IBTC Bank',
    '184': 'Citibank Nigeria',
    '185': 'First City Monument Bank',
    '186': 'Wema Bank',
    '187': 'Jaiz Bank',
    '188': 'Heritage Bank',
    '189': 'Keystone Bank',
    '190': 'Unity Bank',
    '191': 'Zenith Bank',
    '192': 'Standard Chartered Bank',
    '193': 'Sterling Bank',
    '194': 'Polaris Bank',
    '195': 'Titan Trust Bank',
    '196': 'Providus Bank',
    '197': 'Globus Bank',
    '198': 'Parallex Bank',
    '199': 'Suntrust Bank',
    '200': 'Stanbic IBTC Bank',
  };

  return bankNames[bankCode] || `Bank (Code: ${bankCode})`;
};

export const maskAccountNumber = (accountNumber: string): string => {
  if (accountNumber.length < 5) return accountNumber;
  const firstTwo = accountNumber.slice(0, 2);
  const lastThree = accountNumber.slice(-3);
  const masked = '*'.repeat(accountNumber.length - 5);
  return `${firstTwo}${masked}${lastThree}`;
}; 